# Project - 2
## Pandas CSV reader & basic analysis
- Read CSV/Excel into DataFrame and inspect head/tail/types.
- Compute summary stats (mean, median, min, max, count).
- Filter rows, select columns and slice subsets.
- Save filtered results to CSV/excel.

In [1]:
import pandas as pd

### Read CSV / Excel File

In [2]:
# Read CSV
data = pd.read_csv("genz_college_admission_prediction.csv")

### Inspect Data

In [3]:
print("First 5 Rows:")
data.head()

First 5 Rows:

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,3,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,4,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,5,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1

In [4]:
print("Last 5 Rows:")
data.tail()

Last 5 Rows:

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
999995,999996,20,Female,New York,127978,3.98,984,27,94.9,3,6,24,1,2,3.9,2,72.6,76.0,82.0,1
999996,999997,16,Male,Ohio,47661,3.49,940,25,80.6,2,4,206,1,3,6.7,0,88.5,72.9,67.4,1
999997,999998,21,Female,Washington,88044,2.77,1103,16,95.9,0,1,67,0,2,3.7,3,73.1,85.9,77.6,1
999998,999999,17,Female,Virginia,55654,3.71,1208,27,87.8,3,8,24,1,2,2.8,0,72.6,60.9,71.0,1
999999,1000000,18,Male,California,59923,3.41,1241,28,94.0,2,4,184,1,1,1.8,3,70.3,91.7,55.3,1

In [5]:
print("Data Types:")
print(data.dtypes)

Data Types:
student_id                 int64
age                        int64
gender                    object
state                     object
family_income              int64
high_school_gpa          float64
sat_score                  int64
act_score                  int64
attendance_rate          float64
ap_courses                 int64
extracurricular_count      int64
volunteer_hours            int64
leadership_positions       int64
coding_projects            int64
social_media_hours       float64
online_certifications      int64
essay_score              float64
recommendation_score     float64
interview_score          float64
admission_status           int64
dtype: object

In [6]:
print("Dataset Shape:")
print(data.shape)

Dataset Shape:
(1000000, 20)

### Summary Statistics

In [7]:
print("Summary Statistics")
numeric_cols = data.select_dtypes(include="number")

print("Mean:")
print(numeric_cols.mean())

Summary Statistics
Mean:
student_id               500000.500000
age                          19.000294
family_income             71701.069023
high_school_gpa               3.188329
sat_score                  1099.198467
act_score                    23.468139
attendance_rate              91.748151
ap_courses                    2.999739
extracurricular_count         3.999927
volunteer_hours              99.452955
leadership_positions          1.201223
coding_projects               1.999254
social_media_hours            4.506180
online_certifications         1.997953
essay_score                  74.912247
recommendation_score         77.954531
interview_score              72.775141
admission_status              0.881292
dtype: float64

In [8]:
print("Median:")
print(numeric_cols.median())

Median:
student_id               500000.5
age                          19.0
family_income             59877.0
high_school_gpa               3.2
sat_score                  1100.0
act_score                    24.0
attendance_rate              92.0
ap_courses                    3.0
extracurricular_count         4.0
volunteer_hours              91.0
leadership_positions          1.0
coding_projects               2.0
social_media_hours            4.5
online_certifications         2.0
essay_score                  75.0
recommendation_score         78.0
interview_score              73.0
admission_status              1.0
dtype: float64

In [9]:
print("Minimum Values:")
print(numeric_cols.min())

Minimum Values:
student_id                  1.00
age                        16.00
family_income            2124.00
high_school_gpa             0.87
sat_score                 400.00
act_score                   1.00
attendance_rate            63.20
ap_courses                  0.00
extracurricular_count       0.00
volunteer_hours             2.00
leadership_positions        0.00
coding_projects             0.00
social_media_hours          0.00
online_certifications       0.00
essay_score                17.60
recommendation_score       28.80
interview_score             0.50
admission_status            0.00
dtype: float64

In [10]:
print("Maximum Values:")
print(numeric_cols.max())

Maximum Values:
student_id               1000000.0
age                           22.0
family_income             977775.0
high_school_gpa                4.0
sat_score                   1600.0
act_score                     36.0
attendance_rate              100.0
ap_courses                    12.0
extracurricular_count         15.0
volunteer_hours              517.0
leadership_positions           8.0
coding_projects               11.0
social_media_hours            12.9
online_certifications         12.0
essay_score                  100.0
recommendation_score         100.0
interview_score              100.0
admission_status               1.0
dtype: float64

In [11]:
print("Count:")
print(numeric_cols.count())

Count:
student_id               1000000
age                      1000000
family_income            1000000
high_school_gpa          1000000
sat_score                1000000
act_score                1000000
attendance_rate          1000000
ap_courses               1000000
extracurricular_count    1000000
volunteer_hours          1000000
leadership_positions     1000000
coding_projects          1000000
social_media_hours       1000000
online_certifications    1000000
essay_score              1000000
recommendation_score     1000000
interview_score          1000000
admission_status         1000000
dtype: int64

### Select Column

In [12]:
selected_columns = data[['admission_status', 'age']]  

print("Selected Columns:")
print(selected_columns.head())

Selected Columns:
   admission_status  age
0                 1   22
1                 1   19
2                 1   20
3                 1   22
4                 1   18

### Filter Rows

In [13]:
filtered_rows = data[data['age'] > 18]  

print("\nFiltered Rows (age > 18):")
filtered_rows.head()

Filtered Rows (age > 18):

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,3,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,4,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
5,6,20,Female,California,133840,3.81,949,26,94.0,0,2,217,0,1,2.7,2,70.1,81.3,76.8,0

### Slice Subsets

In [14]:
subset = data.iloc[0:10, 0:3]

print("Subset (First 10 Rows, First 3 Columns):")
print(subset)

Subset (First 10 Rows, First 3 Columns):
   student_id  age  gender
0           1   22    Male
1           2   19    Male
2           3   20    Male
3           4   22    Male
4           5   18    Male
5           6   20  Female
6           7   20  Female
7           8   22  Female
8           9   17    Male
9          10   18  Female

### Save Filtered Results

In [15]:
filtered_rows.to_csv("filtered_data.csv", index=False)
print("Filtered data saved successfully!")

Filtered data saved successfully!